# -*- Mode: Python -*- vi:si:et:sw=4:sts=4:ts=4:syntax=python
from cerbero.errors import ConfigurationError

class Recipe(recipe.Recipe):
    name = 'pitivi'
    version = '0.93'
    licenses = [License.GPLv2Plus]
    remotes = {'origin': 'git://git.gnome.org/pitivi'}
    config_sh = 'sh ./autogen.sh --noconfigure && ./configure'
    configure_options = "--disable-help"
    commit = 'origin/master'
    deps = ['gst-editing-services-1.0',
            'gst-python-1.0',
            'gst-libav-1.0',
            'gst-plugins-bad-1.0',
            'gst-plugins-ugly-1.0',
            'clutter-gtk',
            'clutter-gst',
            'numpy',
            'gnome-themes-standard',
            'gnome-icon-theme',
            'gnome-icon-theme-symbolic',
            'shared-mime-info'] # brings in gtk+

    files_bins = ['pitivi']
    files_lang = ['pitivi']
    files_pitivi = ['lib/pitivi/python/pitivi',
                    'share/pitivi/',
                    'share/applications/pitivi.desktop']

    def prepare(self):
        if self.config.variants.python3 is False:
            raise ConfigurationError("Pitivi needs python3. You should set "
                    "\"variants = ['python3']\" in your ~/.cerbero/cerbero.cbc "
                    "configuration file to build it.")
